services:
  - type: web
    name: finance-tracker
    repo: https://github.com/fasihanaeem33-hash/Finance_Tracking
    branch: main
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run aap.py --server.port $PORT --server.address 0.0.0.0
